### PR TITLE
Fixed a bug where components re-rendered too often

### PR DESCRIPTION
**Pull request by jspradlin1-chwy**
devilwjp/vuereact-combined#12

### CODE REVIEW

**Review by dzdrazil — APPROVED** [review]

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
Your modification is a shallow equality check, if the state is an object and a subset of the object is modified, it will not trigger an update of the react component.

For example:
```js
const store = new Vuex.Store({
  state: {
    group: {foo: 1}
  },
  mutations: {
    increment (state) {
      state.group.foo++
    }
  }
})

```

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
According to the design concept of react, the update right of the component should be determined by the component itself, and shallow equality check or deep equality check can be processed inside the react component.

**Comment by jspradlin1-chwy** [comment]
I have verified in production code that when any vuex store property is changed (even if that property is not being used by the connected react component) then the react componetn will re-render.  Additionally, React works by shallow comparison.  If you wish to change a property of an object prop, then you must re-create the object with the changed child.  This is how you properly trigger a refresh in React.   Regardless, connected components (using connectVuex) are re-rendering on any store change, and this is not how it is supposed to work.

**Comment by jspradlin1-chwy** [comment]
As per [this](https://stackoverflow.com/questions/40386128/how-does-a-redux-connected-component-know-when-to-re-render) comment:

> The connect function generates a wrapper component that subscribes to the store. When an action is dispatched, the wrapper component's callback is notified. It then runs your mapState function, **and shallow-compares the result object from this time vs the result object from last time** (so if you were to rewrite a redux store field with its same value, it would not trigger a re-render). If the results are different, then it passes the results to your "real" component" as props.
> 
> Dan Abramov wrote a great simplified version of connect at ([connect.js](https://gist.github.com/gaearon/1d19088790e70ac32ea636c025ba424e)) that illustrates the basic idea, although it doesn't show any of the optimization work. I also have links to a number of articles on [Redux performance](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#redux-performance) that discuss some related ideas.

**Comment by devilwjp** [comment]
> I have verified in production code that when any vuex store property is changed (even if that property is not being used by the connected react component) then the react componetn will re-render. Additionally, React works by shallow comparison. If you wish to change a property of an object prop, then you must re-create the object with the changed child. This is how you properly trigger a refresh in React. Regardless, connected components (using connectVuex) are re-rendering on any store change, and this is not how it is supposed to work.

I understand what you mean, but I have to make sure that any modification triggers the change of the react component, because vuex is mutation and redux is immutable, so if the state of vuex is an object, modifying the subset does not recreate it a new object, so shallow equality checks can't detect state changes, which is more problematic than frequently updating react components.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
In Redux, every time you modify any subset of objects, you will be required to recreate a new object. If this happens in vuex, it will greatly affect performance, because every time you create a new object, vuex will rebind the observer.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
I reviewed your commit in detail again, everything is sensible and can be merged into the master branch.

**Pull request merged**
